[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

# Essential Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Production context
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

# Deploy preview context
[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

# API routes to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
