[build]
  publish = ".next"
  command = "npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- package.json package-lock.json next.config.mjs"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"
  # Explicitly disable Python
  PYTHON_VERSION = ""
  DISABLE_PYTHON = "true"

# Next.js plugin only
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Build contexts
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production", NODE_VERSION = "18.18.0", DISABLE_PYTHON = "true" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "production", NODE_VERSION = "18.18.0", DISABLE_PYTHON = "true" }

[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "production", NODE_VERSION = "18.18.0", DISABLE_PYTHON = "true" }

# Next.js redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
