[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js plugin only
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Build contexts
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production", NODE_VERSION = "18.18.0" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "production", NODE_VERSION = "18.18.0" }

# Next.js redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
